const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '26',
        image: 'image/p1.jpg',
        cat: 'milk',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '96',
        image: 'image/p2.jpg',
        cat: 'milk',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '236',
        image: 'image/p3.jpg',
        cat: 'milk',
        type: 'new',
    },
    {
        id: 4,
        Name: 'product4',
        price: '636',
        image: 'image/p4.jpg',
        cat: 'milk',
        type: 'new',
    },
    {
        id: 5,
        Name: 'product5',
        price: '98',
        image: 'image/p5.jpg',
        cat: 'milk',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '59',
        image: 'image/p6.jpg',
        cat: 'vegetables',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'product7',
        price: '956',
        image: 'image/p7.jpg',
        cat: 'vegetables',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'product8',
        price: '389',
        image: 'image/p8.jpg',
        cat: 'vegetables',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'product9',
        price: '67',
        image: 'image/p9.jpg',
        cat: 'vegetables',
        type: 'top',
    },
    {
        id: 10,
        Name: 'product10',
        price: '76',
        image: 'image/p10.jpg',
        cat: 'vegetables',
        type: 'top',
    },
    
]
export default Homeproduct